The first step to the 0.2
aimclub/SAMPO pull request #70
Opened 2023-12-22 14:13 UTC by StannisMod

This is update about refactorings, fixes and other public version requirements.
- Fixed many (really many) bugs
- Re-read and refactored whole code
- Removed old and unused functions, classes, packages, etc.
- Simplified API of most general functions
- Greatly improved usability
- Simplified (shortened) import paths. For example, `from sampo.scheduler import HEFTScheduler` instead of `from sampo.scheduler.heft.base import HEFTScheduler`
- Added `PreparaionPipeline` to fully control of `WorkGraph` and `list[Contractor]` preparation process separately of scheduling
- Made `WorkGraph` fully serializable by `dill` that enables to fully use `pathos multiprocessing` in our project
- Added `Visualization` as a pipeline for visualization things

2024-01-12 19:46 UTC, vanoha01 requested changes
Changed are requested

2024-01-12 19:46 UTC, vanoha01 commented on sampo/schemas/graph.py
> +def get_start_stage(work_id: str | None = "", rand: Random | None = None) -> GraphNode:
Work_id is None? Is it necessary mention, if default value is empty string

2024-01-12 19:46 UTC, vanoha01 commented on sampo/schemas/graph.py
> +    :param rand: Number generator with a fixed seed, or None for no fixed seed
Remove capital letter

2024-01-12 19:46 UTC, vanoha01 commented on sampo/schemas/graph.py
> +def get_finish_stage(parents: list[GraphNode | tuple[GraphNode, float, EdgeType]], work_id: str | None = "",
The same as above about None

2024-01-12 19:46 UTC, vanoha01 commented on sampo/schemas/graph.py
> +    :param rand: Number generator with a fixed seed, or None for no fixed seed
Capital letter (CP)

2024-01-12 19:46 UTC, vanoha01 commented on sampo/userinput/parser/general_build.py
> +        if 'min_req' in frame.columns and 'max_req' in frame.columns and 'req_volume' in frame.columns:
Was list comprehension replaced by going with loop?

2024-01-13 11:03 UTC, StannisMod commented on sampo/scheduler/genetic/operators.py
> +    def prepare(resources_names: Iterable[str]) -> Callable[[list[ChromosomeType]], list[Schedule]]:
No, check the documentation of `Callable`

2024-01-13 11:04 UTC, StannisMod commented on sampo/scheduler/genetic/operators.py
> +    def prepare(resources_names: Iterable[str]) -> Callable[[list[ChromosomeType]], list[Schedule]]:
The same as above

2024-01-13 11:23 UTC, vanoha01 approved these changes
Approved

2024-01-13 11:25 UTC, merged